version: '3.4'
services:
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - redProyecto

  apitiempo:
    image: proyecto_apitiempo 
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    ports:
      - 5000:5000
    networks:
        - redProyecto
        
  apiconsola:
    image: proyecto_apiconsola
    build:
        context: .
        dockerfile: Dockerfile.cons
    restart: always
    networks:
      - redProyecto
networks:
  redProyecto: